"""Embed the repository's SD-era motion programs in ESP flash before each build."""

from __future__ import annotations

import argparse
from pathlib import Path


if "Import" in globals():  # PlatformIO executes pre-build scripts without __file__.
    Import("env")
    PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
else:
    PROJECT_DIR = Path(__file__).resolve().parents[1]
REPOSITORY_DIR = PROJECT_DIR.parent
SOURCE_DIR = REPOSITORY_DIR / "gcodes"
OUTPUT = PROJECT_DIR / "src" / "embedded_gcodes.h"
RANDOM_FILES = tuple("input.txt" if index == 1 else f"input{index}.txt" for index in range(1, 8))
PRESET_FILES = tuple(f"pos{index}.txt" for index in range(1, 4))
DELIMITER = "LUMIAC_GCODE"


def read_program(filename: str, loop: bool) -> str:
    content = (SOURCE_DIR / filename).read_text(encoding="utf-8").replace("\r\n", "\n").rstrip("\n") + "\n"
    if f"){DELIMITER}\"" in content:
        raise ValueError(f"{filename}: reserved C++ raw-string delimiter in G-code")

    commands = [line.split(";", 1)[0].strip() for line in content.splitlines()]
    commands = [line for line in commands if line]
    allowed = ("G1 ", "G28 ", "G90", "M204 ", "@LOOP")
    if any(not line.startswith(allowed) or len(line) >= 96 for line in commands):
        raise ValueError(f"{filename}: unsupported or oversized G-code command")
    if (commands[-1] == "@LOOP") != loop or (loop and commands.count("@LOOP") != 1):
        raise ValueError(f"{filename}: unexpected loop directive")
    return content


def render_header() -> str:
    unique: dict[str, str] = {}
    for filename in (*RANDOM_FILES, *PRESET_FILES):
        content = read_program(filename, loop=filename in RANDOM_FILES)
        unique.setdefault(content, f"kProgram{len(unique)}")

    lines = [
        "// Generated by scripts/embed_gcodes.py from ../../gcodes. Do not edit by hand.",
        "#pragma once",
        "#include <Arduino.h>",
        "namespace embedded_gcodes {",
        "struct Program { const char* name; const char* text; bool loop; };",
    ]
    for content, symbol in unique.items():
        lines.append(f'static const char {symbol}[] PROGMEM = R"{DELIMITER}({content}){DELIMITER}";')

    for kind, filenames, loop in (("randomPrograms", RANDOM_FILES, True), ("presetPrograms", PRESET_FILES, False)):
        lines.append(f"static const Program {kind}[] = {{")
        for filename in filenames:
            content = read_program(filename, loop)
            lines.append(f'  {{ "/gcodes/{filename}", {unique[content]}, {str(loop).lower()} }},')
        lines.append("};")
    lines.extend(("} // namespace embedded_gcodes", ""))
    return "\n".join(lines)


def generate(check: bool = False) -> bool:
    rendered = render_header()
    if check:
        return OUTPUT.exists() and OUTPUT.read_text(encoding="utf-8") == rendered
    if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
        with OUTPUT.open("w", encoding="utf-8", newline="\n") as header:
            header.write(rendered)
    return True


if "Import" in globals():  # PlatformIO pre-build hook
    generate()
elif __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the embedded header is out of date")
    args = parser.parse_args()
    if not generate(check=args.check):
        parser.exit(1, f"Outdated {OUTPUT}; run this script without --check.\n")
